---
title: "STT380-HW4"
author: "Jimmy Gray-Jones"
date: "2022-10-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("GGally", dependencies = TRUE, INSTALL_opts = c('--no-lock'))

```

```{r}
penguins = read.csv("penguins.csv")

penguins_numeric = penguins[2:5]
```

```{r, echo=TRUE}

#1) Load the penguins dataset available in D2L. Produce a pairs plot with ggpairs, colored by species. Then use the pairs plot to answer the following questions.

GGally::ggpairs(penguins,mapping = ggplot2::aes(color = penguins$species))

#a. Which species has the most members in the dataset?

x = y = z = 0

for(i in penguins$species)
{
  if(i=="Adelie")
  {
    x = x + 1
  }
  if(i=="Chinstrap")
  {
    y = y + 1
  }
  if(i=="Gentoo")
  {
    z = z + 1
  }
}

cat('Adelie:',x,'Chinstrap',y,'Gentoo',z)

#Adelie has the most species in the given data

#b. Which other variable has the highest correlation with body mass (for the overall dataset)?

cor(penguins_numeric)

#Flipper Length has the highest correlation with body mass


#c. For Adelie, which other variable has the highest correlation with body mass?

adelie_data = dplyr::filter(penguins,penguins$species=='Adelie')

cor(adelie_data[2:5])

#Highest correlation with body mass for Adelie is bill_depth_mm

#d. For each field, which species have similar values according to the histogram?

#Adelie and Gentoo seems to have similar values, according to the pairs histogram

```

```{r, echo=TRUE}

#2) Take the function f(x, y, z) = x2 – 3x + y4 – 3y + z2 + 10z + cos(xyz). Find the location of the minimum value. Use c(0, 0 ,0) as the initialization location. Try different initialization locations. Can you find different locations for minima? If you see multiple ones, which one seems to be a global minimum?

f_xyz = function(x,y,z)
{
  return (x**2 - 3*x + y**4 - 3*y +z**2 + 10*z + cos(x*y*z))
}

#Initialization location; Output = 1
f_xyz(0,0,0)

#Additional Local Minimums
cat('Local Minimum:',f_xyz(1,0,0))

cat('Local Minimum:',f_xyz(2,0,0))

cat('Local Minimum:',f_xyz(0,1,0))

cat('Local Minimum:',f_xyz(1,1,0))

#Lowest value in function that I found

cat('Global Minimum:',f_xyz(1,1,-4))

```

#3) One the interval [1, ∞] a probability distribution is defined as p(x) = /x(+1) . Given the sample {2, 3, 2.5, 3, 1.6, 1.4, 1.3, 1.8, 1.9, 2.4, 4.6}, find the log-likelihood, and then calculate the maximum likelihood estimate for the parameter . (Hint: the likelihood function will look very similar to what we had in ICA 14, #2)

```{r, echo=TRUE}

#Assuming this is a normal distribution
samp = c(2,3,2.5,3,1.6,1.4,1.3,1.8,1.9,2.4,4.6)

LL = function(alpha) log(alpha) /(sum(samp)**(alpha+1))

LL

optimize(LL,c(0,length(samp)),maximum=TRUE)

```
```{r, echo=TRUE}


#4) The beta distribution on the interval 0 \< x \< 1 has the form Where  is the gamma function. The two parameters α and β are positive constants. Fortunately, you do not need to use this messy expression, since R has a function to express the probability density: p(x) = dbeta(x, alpha, beta)
beta_samp = read.csv("beta_samp.csv")

#a. Take the sample data in D2L called beta_samp.csv. Construct the log-likelihood function using dbeta.

x = 0:1

LL2 = function(x) dbeta(sum(beta_samp[2]),0,1)

#b. Use the optim function in R to find the maximum likelihood estimate for the parameters.

optimized_LL2 = optim(c(0,1),LL2,beta_samp[2])


#c. Graph the beta distribution for the given parameters between 0 \< x \< 1.

#plot(x,optimized_LL2[2])

```

```{r, echo=TRUE}
#5. With the penguins dataset, construct a 99% two-sided confidence interval for the mean value for body mass with the t-distribution. Then do the same for each species individually.

adelie_data = dplyr::filter(penguins,penguins$species=='Adelie')
chinstrap_data = dplyr::filter(penguins,penguins$species=='Chinstrap')
gentoo_data = dplyr::filter(penguins,penguins$species=='Gentoo')


SE = sd(penguins$body_mass_g) / sqrt(length(penguins$body_mass_g))

CI_99 = mean(penguins$body_mass_g) + SE*qt(.01,length(penguins$body_mass_g)-1)

CI_01 = mean(penguins$body_mass_g) + SE*qt(.99,length(penguins$body_mass_g)-1)

CI_99_Adelie = mean(adelie_data$body_mass_g) + SE*qt(.01,length(adelie_data$body_mass_g)-1)

CI_01_Adelie = mean(adelie_data$body_mass_g) + SE*qt(.99,length(adelie_data$body_mass_g)-1)

CI_99_Chinstrap = mean(chinstrap_data$body_mass_g) + SE*qt(.01,length(chinstrap_data$body_mass_g)-1)

CI_01_Chinstrap = mean(chinstrap_data$body_mass_g) + SE*qt(.99,length(chinstrap_data$body_mass_g)-1)

CI_99_Gentoo = mean(gentoo_data$body_mass_g) + SE*qt(.01,length(gentoo_data$body_mass_g)-1)

CI_01_Gentoo = mean(gentoo_data$body_mass_g) + SE*qt(.99,length(gentoo_data$body_mass_g)-1)
```